project:
  type: default
  output-dir: _output

format:
  html:
    theme: cosmo
    css: assets/cv.css
    self-contained: true
    toc: false
    number-sections: false
  pdf:
    documentclass: article
    geometry:
      - top=20mm
      - bottom=20mm
      - left=18mm
      - right=18mm
    fontsize: 10pt
    colorlinks: true
    linkcolor: "black"
    urlcolor: "black"
    include-in-header: assets/cv-preamble.tex
